"use strict";
console.log("Hello World");
console.log("Hello Udemy.com");
console.log("Hello, Hello World!");
console.log("Hello");
console.log("Hello, Hello");
console.log("Hello World, Hello World!");
console.log("Testing");
console.log("Testing2 -> Hello World!");
console.log("Testing3 -> Hello World!; Hello World!");
